// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_api.Data;

#nullable disable

namespace dotnet_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109200000_ChangeRawOutputToLongText")]
    partial class ChangeRawOutputToLongText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dotnet_api.Models.AnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("average_score");

                    b.Property<string>("BaseCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("base_commit_sha");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("default_branch");

                    b.Property<int>("FilesAnalyzed")
                        .HasColumnType("int")
                        .HasColumnName("files_analyzed");

                    b.Property<string>("HeadCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("head_commit_sha");

                    b.Property<string>("RawOutput")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("raw_output");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("int")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<int>("TotalIssues")
                        .HasColumnType("int")
                        .HasColumnName("total_issues");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_runs_status");

                    b.HasIndex("RepositoryId", "BranchName")
                        .HasDatabaseName("idx_runs_repo_branch");

                    b.HasIndex("RepositoryId", "BaseCommitSha", "HeadCommitSha")
                        .IsUnique()
                        .HasDatabaseName("idx_runs_repo_commits");

                    b.ToTable("analysis_runs");
                });
#pragma warning restore 612, 618
        }
    }
}
