// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_api.Data;

#nullable disable

namespace dotnet_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dotnet_api.Models.AnalysisIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<int?>("LineEnd")
                        .HasColumnType("int")
                        .HasColumnName("line_end");

                    b.Property<int?>("LineStart")
                        .HasColumnType("int")
                        .HasColumnName("line_start");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("RuleId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("rule_id");

                    b.Property<int>("RunId")
                        .HasColumnType("int")
                        .HasColumnName("run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("idx_ai_run");

                    b.HasIndex("RunId", "Severity")
                        .HasDatabaseName("idx_ai_run_sev");

                    b.ToTable("analysis_issues");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("JSON")
                        .HasColumnName("metrics_json");

                    b.Property<int>("RunId")
                        .HasColumnType("int")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("idx_am_run");

                    b.ToTable("analysis_metrics");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("average_score");

                    b.Property<string>("BaseCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("base_commit_sha");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("default_branch");

                    b.Property<int>("FilesAnalyzed")
                        .HasColumnType("int")
                        .HasColumnName("files_analyzed");

                    b.Property<string>("HeadCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("head_commit_sha");

                    b.Property<string>("RawOutput")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("raw_output");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("int")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<int>("TotalIssues")
                        .HasColumnType("int")
                        .HasColumnName("total_issues");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_runs_status");

                    b.HasIndex("RepositoryId", "BranchName")
                        .HasDatabaseName("idx_runs_repo_branch");

                    b.HasIndex("RepositoryId", "BaseCommitSha", "HeadCommitSha")
                        .IsUnique()
                        .HasDatabaseName("idx_runs_repo_commits");

                    b.ToTable("analysis_runs");
                });

            modelBuilder.Entity("dotnet_api.Models.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("clone_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("full_name");

                    b.Property<long>("GithubRepoId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_repo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GithubRepoId")
                        .IsUnique()
                        .HasDatabaseName("idx_repos_github_repo_id");

                    b.HasIndex("UserId");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("dotnet_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GithubAccessToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("github_access_token");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisIssue", b =>
                {
                    b.HasOne("dotnet_api.Models.AnalysisRun", "Run")
                        .WithMany("Issues")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisMetric", b =>
                {
                    b.HasOne("dotnet_api.Models.AnalysisRun", "Run")
                        .WithMany("Metrics")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisRun", b =>
                {
                    b.HasOne("dotnet_api.Models.Repository", "Repository")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("dotnet_api.Models.Repository", b =>
                {
                    b.HasOne("dotnet_api.Models.User", "User")
                        .WithMany("Repositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnet_api.Models.AnalysisRun", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("dotnet_api.Models.Repository", b =>
                {
                    b.Navigation("AnalysisRuns");
                });

            modelBuilder.Entity("dotnet_api.Models.User", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
