apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dotnet-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: kv-v2
  mount: secret
  path: codereview/dotnet-api/app
  refreshAfter: 60s
  vaultAuthRef: dotnet-api-vault-auth
  destination:
    name: dotnet-secrets
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mysql-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: kv-v2
  mount: secret
  path: codereview/dotnet-api/mysql
  refreshAfter: 60s
  vaultAuthRef: dotnet-api-vault-auth
  destination:
    name: mysql-secret
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: kv-v2
  mount: secret
  path: codereview/grafana/config
  refreshAfter: 60s
  vaultAuthRef: grafana-vault-auth
  destination:
    name: grafana-secrets
    create: true
    overwrite: true
